#!/usr/bin/env python3
import os
import re

repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def compile_tiers():
    print("Compiling tiers...")
    # 1. common-considerations.md -> slim_core.md
    common_path = os.path.join(repo_root, "common/common-considerations.md")
    with open(common_path, 'r') as f:
        common_content = f.read()
    
    # Extract CRITICAL rules
    slim_rules = []
    blocks = common_content.split('---')
    for block in blocks:
        if "**Severity:** CRITICAL" in block:
            slim_rules.append(block.strip())
            
    slim_core_content = """# Secure Planning Framework — Slim Core Baseline
**Generated by Tier Compiler**

> This file contains the NON-NEGOTIABLE, always-applicable baseline rules.
> If the application is high-risk (financial, multi-agent, healthcare), you MUST ALSO read `common/common-considerations.md` for the full set of extended baseline controls.

---

""" + "\n\n---\n\n".join(slim_rules) + "\n\n---\n"
    
    slim_path = os.path.join(repo_root, "common/slim_core.md")
    with open(slim_path, 'w') as f:
        f.write(slim_core_content)
    print(f"Generated {slim_path} with {len(slim_rules)} rules.")
    
    # We could also compile baseline vs full for AI/MCP, but SKILL.md will just use the "Risk Tier: baseline" vs "elevated" tags in the files directly to save token costs?
    # If the LLM reads the file, it reads the whole file. To save tokens, we MUST split them into separate files.
    # Let's split agentic_ai, llm_governance, mcp_server into _baseline.md and _extended.md
    
    ai_files = [
        "domains/ai/agentic_ai_rules.md",
        "domains/ai/llm_governance_rules.md",
        "domains/mcp/mcp_server_rules.md"
    ]
    
    for rel_path in ai_files:
        full_path = os.path.join(repo_root, rel_path)
        with open(full_path, 'r') as f:
            content = f.read()
            
        blocks = content.split('---')
        header = blocks[0]
        baseline_rules = []
        extended_rules = []
        
        for block in blocks[1:]:
            if "Risk Tier: baseline" in block:
                baseline_rules.append(block.strip())
            elif "Rule ID:" in block:
                extended_rules.append(block.strip())
                
        base_name = os.path.splitext(rel_path)[0]
        
        # Write baseline
        with open(os.path.join(repo_root, f"{base_name}_baseline.md"), 'w') as f:
            f.write(header + "---\n\n" + "\n\n---\n\n".join(baseline_rules) + "\n")
            
        # Write extended
        with open(os.path.join(repo_root, f"{base_name}_extended.md"), 'w') as f:
            f.write(header + "> NOTE: These are ELEVATED and HIGH-ASSURANCE rules.\n\n---\n\n" + "\n\n---\n\n".join(extended_rules) + "\n")

def generate_adapters():
    print("Generating IDE adapters...")
    skill_path = os.path.join(repo_root, "SKILL.md")
    with open(skill_path, 'r') as f:
        skill_content = f.read()
        
    # Strip the yaml frontmatter from SKILL.md
    if skill_content.startswith('---'):
        parts = skill_content.split('---', 2)
        if len(parts) >= 3:
            skill_content = parts[2].strip()
            
    header = "<!-- GENERATED ADAPTER: DO NOT EDIT. Modify SKILL.md and run scripts/build_pipeline.py -->\n\n"
    final_content = header + skill_content
    
    adapters = [
        ".cursorrules",
        ".windsurfrules",
        ".github/copilot-instructions.md"
    ]
    
    for a in adapters:
        p = os.path.join(repo_root, a)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, 'w') as f:
            f.write(final_content)
        print(f"Generated {a}")

if __name__ == '__main__':
    compile_tiers()
    generate_adapters()
    print("Build pipeline completed.")
